### PR TITLE
6.x: Rebuild for Python 3.11

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Do you want to add a global pin for qt6-main? that way the migrator can help this soft transition?

**Comment by jschueller** [comment]
I thought we had to do something like qt-main to tell in which branches the migrations should land

**Comment by hmaarrfk** [comment]
Yes. we do. But the "core" dependency wouldn't be migrated. I guess we can start locally, and just see what happens. Maintain the qt6-main dependency.

**Comment by hmaarrfk** [comment]
```
bot:
  abi_migration_branches:
  - pyside6
```

**Pull request merged**
