### PR TITLE
BUG: Backport PyOS_InputHook bug fix for PYSIDE-2192

### LINKED ISSUE #226: Upstream bug breaks interactive plotting in Matplotlib, what to do?
Hello! So there's an upstream bug in PySide6 (which has been present since the PySide2 days) that prevents interactive Matplotlib plots from showing up:

https://github.com/matplotlib/matplotlib/issues/15359

Importantly, PyQt6 doesn't have this issue.

The problem is due to PySide6's not implementing the `PyOS_InputHook` API. We'd opened a [bug report](https://bugreports.qt.io/browse/PYSIDE-2192) upstream many months ago, but nothing's really happening.

Since PyQt6 is not available for `conda-forge` and we have to stick with PySide6, interactive plotting is now broken for us.

A [fix](https://codereview.qt-project.org/c/pyside/pyside-setup/+/454254) was proposed but never merged, since apparently the CI runs wouldn't finish on Windows.

I was wondering if we could apply this patch at least for non-Windows platforms here, since there's no activity anymore upstream? Of course, the easiest for me (as a user) would be to just use PyQt6 instead, but there are no `conda-forge` packages. This is a really bad situation to be in now, as it means I'm stuck with either a broken PySide6 or an (old) PyQt5 for the time being...

### PR DESCRIPTION
**Pull request by larsoner**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #226

### CODE REVIEW

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
Will have to wait for https://github.com/conda-forge/status/issues/181 / https://conda-forge.org/status/

**Comment by larsoner** [comment]
@conda-forge-admin please restart ci

**Review by hoechenberger — APPROVED** [review]

**Comment by larsoner** [comment]
All green @hmaarrfk !

**Comment by hmaarrfk** [comment]
Ok. Let's see. Good luck all!!!

**Pull request merged**
