### PR TITLE
try to build with qt5.9

### PR DESCRIPTION
**Pull request by looooo**
mainly a test how good the compatibility between defaults and conda-forge is.

### CODE REVIEW

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
- for windows I guess we have to disable python2:
```
failed to get install actions, retrying.  exception was: The following specifications were found to be in conflict:
  - clangdev
  - vc=9
Use "conda info <package>" to see the dependencies for each package.
```

- osx has some clang config problem
- linux has a linking problem:
```
/lib/libQt5UiTools.a(quiloader.o): unrecognized relocation (0x2a) in section `.text'
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: final link failed: Bad value
```

**Comment by looooo** [comment]
TODO: CLANG_INSTALL_DIR must be set for osx.

**Comment by rth** [comment]
Thanks for working on this! You may find the discussion in https://github.com/conda-forge/qt-feedstock/issues/53 useful.

**Comment by albertosottile** [comment]
Actually, the Qt for Python team confirmed that only 5.11 will be maintained, so the 5.9 branch will soon be outdated.

**Comment by looooo** [comment]
ok, so better wait for a qt5.11 package... but i guess it will take some time until this will be available.

**Comment by looooo** [comment]
I guess the linker problem for linux will be resolved with using the tool-chain from anaconda. So basically this shows, that conda-forge is not yet fully compatible with anaconda packages.

**Comment by looooo** [comment]
@mingwandroid any ideas why this fails on linux?
```
.../lib/libQt5UiTools.a(quiloader.o): unrecognized relocation (0x2a) in section `.text'
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: final link failed: Bad value
```

**Comment by mingwandroid** [comment]
Sorry I have never used devtoolset. I won't either.

**Comment by jschueller** [comment]
you can revive this whenever qt is updated: conda-forge/qt-feedstock#53

**Comment by mingwandroid** [comment]
Qt 5.11 is not a requirement of pyside2, in fact it's compatible with Qt 5.6 and above.

**Comment by rth** [comment]
> Qt 5.11 is not a requirement of pyside2, in fact it's compatible with Qt 5.6 and above.

In theory maybe, but in practice their first release "Technical preview" only supports Qt 5.11 as far as I understand (cf https://wiki.qt.io/Qt_for_Python)..

**Comment by h404bi** [comment]
Just FYI. Pyside2 for Qt 5.11 has been released:
https://download.qt.io/official_releases/QtForPython/pyside2/

while Pyside2 for Qt 5.6 and Qt 5.9 is on snapshots status:
https://download.qt.io/snapshots/ci/pyside/5.6/latest/pyside2/
https://download.qt.io/snapshots/ci/pyside/5.9/latest/pyside2/

**Pull request closed without merging**
