### PR TITLE
WIP: V5.15.3

### PR DESCRIPTION
**Pull request by hmaarrfk**
building off @looooo 's great work, but I don't want to create needless conflicts with them

https://github.com/conda-forge/pyside2-feedstock/pull/109/

- [x] Linux 64 builds
- [x] Mac OSX amd64 builds
- [ ] Windows amd64 builds (python 3.8 still broken)
- [ ] Cleanup defunct patch

Estimated build time: 90 mins.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
I think I understand why linux is failing. Basically we have to rebuild the shortcuts to the `uic` and `rcc` tools.

I don't understand why windows is failing to import shiboken. Maybe it is in the wrong build/host environment.

As for OSX, I think shiboken needs to be installed in the `host` environemnt (x86) and not (arm) so I'm trying to build out the recipe in my own channel to see how things work:
https://github.com/hmaarrfk/shiboken2-feedstock

**Comment by looooo** [comment]
this looks promising. Do you know what the status of qt-main 5.15.3 is. For osx_arm it is needed but I it's seems like it is still conflicting with qtwebengine.

**Comment by hmaarrfk** [comment]
do you mean we need 5.15.3 and not 5.15.2 for osx + arm?

**Comment by hmaarrfk** [comment]
I'm not sure why windows is failing to import shiboken. I'm going to try to build it out with a separate shiboken package.

I have one ready: https://dev.azure.com/markharfouche0439/feedstocks/_build/results?buildId=51&view=results, i will have to upload it.

**Comment by hmaarrfk** [comment]
the build logs for shiboken2 i have linked to show the same error as here. it just seems to not like clang for OSX-arm.

**Comment by hmaarrfk** [comment]
Truthfully, I'm not too sure why you enabled M1 during this update. It requires cross compilation which isn't too easy to handle on a first pass.

It seems Qt made some good progress recently for PySide6, but it is not really trivial to backport such changes.

I might stop before "M1" builds. and let somebody else take those over.

**Comment by hmaarrfk** [comment]
You can see their progress here: https://bugreports.qt.io/browse/PYSIDE-802?focusedCommentId=418104&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender


I think windows is not searching in all the right directories.

**Comment by looooo** [comment]
@hmaarrfk I tried to compile for osx_arm64 and it worked but then this happened:
```
ld_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/libshiboken2.cpython-310-darwin.5.15.3.dylib'
libc++abi: terminating with uncaught exception of type std::runtime_error: codesign_failed: 0
```

**Comment by hmaarrfk** [comment]
i'm not too sure. this seems like it might be related to https://github.com/conda-forge/miniforge/issues/190
@conda-forge/help-osx-arm64

**Comment by looooo** [comment]
I tried to install Xcode but I am still running into the same issue with osx_arm.

**Comment by hmaarrfk** [comment]
is it ok if we leave the architecture migrations out of this one? We can focus on them more cleanly in a subsequent PR. We can likely get them to work on the CI with correct setttings for cross compilation.

**Comment by hmaarrfk** [comment]
At this stage, it seems that the only thing to do is to copy the entry points correctly for windows.

**Comment by hmaarrfk** [comment]
sigh, i force pushed, now i only have 1/4 windows builds instead of 3/4.

**Comment by hmaarrfk** [comment]
Well it seems that I'm missing a few patches for windows and Python 3.8+. However, I'm not sure which one.

I don't know if you have time to take over @looooo but that would be helpful.

**Pull request closed without merging**
