### PR TITLE
Add uic and rcc entry points

### PR DESCRIPTION
**Pull request by n-elie**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
I remember we manually had to move scripts around for pyside2.

**Comment by hmaarrfk** [comment]
I also noticed that the script did little other than to call

```
uic -g python
```

Most of the script tried to work around issues of finding the binary when shipped within python's virtual environments.

**Comment by n-elie** [comment]
@hmaarrfk Thanks for the hints. I managed to get something working on linux and osx, but the build is failing for some reasons in windows and aarch64. These failures does seem to be related to my modifications.

**Comment by hmaarrfk** [comment]
Does or "does not"?

**Comment by jschueller** [comment]
Could you try rebase ? the clang pinning and patch should not be necessary anymore

**Comment by n-elie** [comment]
@jschueller I was trying to rebase but it seems you are working on it in #182

**Comment by jschueller** [comment]
yes, I included your work

**Pull request closed without merging**
