### PR TITLE
disable propagation of PY_LIMITED_API to dependent targets

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
#232

**Comment by hmaarrfk** [comment]
I'm not too sure if removing this file would break things:

```
  cp -v ./tests/pysidetest/testbinding.abi3.so ${SP_DIR}
```

are you able to use the limited ABI in your package? it seems that more and more packages are moving in that direction. May I ask if there is 1 particular function that needs it or is it more wide spread?

**Comment by looooo** [comment]
> are you able to use the limited ABI in your package?

not yet. Also I don't think the transition will happen for the next release.

>May I ask if there is 1 particular function that needs it or is it more wide spread?

From looking at the build-errors it seems like it's used in more than one place.

I am wondering why the LIMITED_API is propragated to downstream packages? Is there any reason for this?

**Comment by looooo** [comment]
this addition changes in `${PREFIX}/lib/cmake/Shiboken6/Shiboken6Targets.cmake`
this:
```
set_target_properties(Shiboken6::libshiboken PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "Py_LIMITED_API=0x03060000;NDEBUG"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/shiboken6"
)
```
to
```
set_target_properties(Shiboken6::libshiboken PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "NDEBUG"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/shiboken6"
)
```

In my mind Pyside6/Shiboken6 should not propagate the PY_LIMITED_API to downstram packages. At least it makes no sense for me.

**Comment by hmaarrfk** [comment]
it may be appropriate for us to patch that out and simultaneously issue a bug report upstream.

**Comment by hmaarrfk** [comment]
ps it may have been due to https://bugreports.qt.io/browse/PYSIDE-1775?jql=text+%7E+%22PY_LIMITED_API%22

i think it would be good if you could open an issue upstream, and we can "track it" even if for years to come...

**Comment by looooo** [comment]
done: https://bugreports.qt.io/browse/PYSIDE-2822

**Comment by jschueller** [comment]
lets not patch, instead set FORCE_LIMITED_API can be set to OFF

**Comment by jschueller** [comment]
see #241

**Pull request closed without merging**
