### PR TITLE
MNT: Re-rendered with conda-build 3.17.8, conda-smithy 3.3.3, and con…

### PR DESCRIPTION
**Pull request by jschueller**
…da-forge-pinning 2019.04.25

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Don't forget to bump the build number.

**Comment by looooo** [comment]
can we do anything about this one?

**Comment by jschueller** [comment]
Yes, I guess we'll have to try to look at the upstream issues, patches, maybe even ask them what is this error about.

**Comment by looooo** [comment]
error from appveyor:
```
[ 96%] Running generator for 'shiboken2'...
NMAKE : fatal error U1077: 'C:\bld\pyside2_1556702770585\work\sources\shiboken2\build\generator\shiboken2.exe' : return code '0xc0000135'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
```

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
@conda-forge/core is it somehow possible to re-run azure to see the build-output?

**Comment by jschueller** [comment]
I added a commit to trigger the rebuild

**Comment by looooo** [comment]
thanks @jschueller 
I copy the errors to not loose them again:

<details>
    <summary>linux</summary>
<pre><code>
[  3%] Running generator for QtCore...
qt.shiboken: (core) Unknown attribute for 'add-function': 'allow-thread'
(core) clang_parseTranslationUnit2(0x0, cmd[9]=-isystem /home/conda/feedstock_root/build_artifacts/pyside2_1558535108668/_build_env/lib/clang/8.0.0/include -std=c++14 -fPIC -fno-exceptions -Wno-constant-logical-operand -I/home/conda/feedstock_root/build_artifacts/pyside2_1558535108668/work/sources/pyside2/PySide2 -I/home/conda/feedstock_root/build_artifacts/pyside2_1558535108668/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/qt/ /tmp/QtCore_global_TJ1708.hpp)
/home/conda/feedstock_root/build_artifacts/pyside2_1558535108668/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/qt/QtCore/qglobal.h:45:12: fatal error: 'type_traits' file not found
(core) Errors in /tmp/QtCore_global_TJ1708.hpp:
/home/conda/feedstock_root/build_artifacts/pyside2_1558535108668/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/qt/QtCore/qglobal.h:45:12: fatal: 'type_traits' file not found
   /tmp/QtCore_global_TJ1708.hpp:1:10: note: in file included from /tmp/QtCore_global_TJ1708.hpp:1:
   /home/conda/feedstock_root/build_artifacts/pyside2_1558535108668/work/sources/pyside2/build/PySide2/QtCore_global.h:41:10: note: in file included from /home/conda/feedstock_root/build_artifacts/pyside2_1558535108668/work/sources/pyside2/build/PySide2/QtCore_global.h:41:
   /home/conda/feedstock_root/build_artifacts/pyside2_1558535108668/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/qt/QtCore/qnamespace.h:43:10: note: in file included from /home/conda/feedstock_root/build_artifacts/pyside2_1558535108668/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/qt/QtCore/qnamespace.h:43:

:0: error: Unable to retrieve code snippet. [other]
</code></pre>
</details>

<details>
    <summary>osx</summary>
<pre><code>
[ 96%] Running generator for 'shiboken2'...
dyld: Library not loaded: @rpath/libclang.dylib
  Referenced from: /usr/local/miniconda/conda-bld/pyside2_1558535148479/work/sources/shiboken2/build/generator/shiboken2
  Reason: image not found
/bin/sh: line 1:  8840 Abort trap: 6           /usr/local/miniconda/conda-bld/pyside2_1558535148479/work/sources/shiboken2/build/generator/shiboken2 --project-file=/usr/local/miniconda/conda-bld/pyside2_1558535148479/work/sources/shiboken2/build/shibokenmodule/shibokenmodule.txt
make[2]: *** [shibokenmodule/shiboken2/shiboken2_module_wrapper.cpp] Error 134
make[1]: *** [shibokenmodule/CMakeFiles/shibokenmodule.dir/all] Error 2
</code></pre>
</details>

<details>
    <summary>win py37 / py36 azure</summary>
<pre><code>
The following tests FAILED:
	125 - QtCore_qfile_test (Failed)
	127 - QtCore_qflags_test (Failed)
	374 - QtSql_qsqldatabaseandqueries_test (Failed)
	395 - QtPositioning_positioning (Failed)
	423 - QtScriptTools_debugger_test (Failed)
</code></pre>
</details>

<details>
    <summary>win py27 azure</summary>
<pre><code>
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - qt=5.9 -> vc[version='>=14.1,<15.0a0']
</code></pre>
</details>

**Comment by looooo** [comment]
a first suggestion regarding the linux-error from pyside2-gitter channel:
https://bugreports.qt.io/browse/PYSIDE-787

**Comment by looooo** [comment]
Not sure but maybe we need clang and llvm not only in build-deps but also host-deps and maybe also in run-deps. I think shiboken needs it at runtime to generate the bindings.

**Comment by jschueller** [comment]
Why would it need it in host too ?
At runtime ? Not sure if other packages use shiboken, does the pip package provide llvm ?

**Comment by looooo** [comment]
> Why would it need it in host too ?  

To solve the build-issue on osx. But I am not sure if it is a good idea.

> At runtime ?

You are right, if only pyside2 is of interest it doesn't make sense to put llvm/clang into run-dependencies.

**Comment by looooo** [comment]
Regarding gutter conversation, clang should be in host-deps because the clang library is used. Maybe you can try that @jschueller .

**Comment by jschueller** [comment]
Indeed, the build goes much further on osx

**Comment by isuruf** [comment]
On Linux you also need gxx_impl_linux-64 at runtime for the C++ headers

**Comment by jschueller** [comment]
You mean in the host section ?

**Comment by looooo** [comment]
regarding pyside2 gitter-conversation the problem on linux is related to https://bugreports.qt.io/browse/PYSIDE-787 . At least it is a similar error message.

**Comment by jschueller** [comment]
@isuruf could you explain your suggestion to add gxx_impl_linux-64 ?

**Comment by looooo** [comment]
Are we using wrong headers for linux? I guess headers from gxx_impl_linux-64 are currently not used.

**Comment by looooo** [comment]
:+1: thanks for getting this one done.

**Comment by jschueller** [comment]
: )

**Pull request merged**
