### PR TITLE
Ensure dist info is provided so pip recognizes installation

### PR DESCRIPTION
**Pull request by ksunden**
This addresses the concerns brought up in #84.
Official source install instructions for pyside instruct to use `python setup.py install` with a number of options.
Since we are installing to a particular location, we use cmake/make to install instead, which makes sense, but does not handle adding the dist-info folder which is what pip looks for to see that a package is installed.

This PR adds that by using the more targeted `python setup.py dist-info`.

To do so on py3.8/3.9, I had to disable the python version check in setup.py (which looks at classifiers, does not use `python-requires`), hence the additional patch file.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ksunden** [comment]
@conda-forge-admin, please rerender

**Comment by ksunden** [comment]
Had to add an explicit gxx build dep for some reason that I do not fully understand.... (The setup.py dist_info calls failed without it, indicating gxx could not be run) If that is a problem, I can look into it more (perhaps an env var could be set or something).

**Comment by ksunden** [comment]
@jschueller Do you have any opinions on this packaging change to allow pyside2 to integrate better on installed systems?

**Comment by ksunden** [comment]
@jschueller thoughts?

**Comment by wolfv** [comment]
@ksunden @jan-janssen would one of you be willing to become additional maintainers of this feedstock?

**Comment by jan-janssen** [comment]
> @ksunden @jan-janssen would one of you be willing to become additional maintainers of this feedstock?

Sure, I am happy to - I opened a corresponding pull request https://github.com/conda-forge/pyside2-feedstock/pull/95

**Pull request merged**
