### PR TITLE
[pyside6] Re-enable osx-arm

### PR DESCRIPTION
**Pull request by h-vetinari**
Towards https://github.com/conda-forge/pyside2-feedstock/issues/159

### CODE REVIEW

**Comment by h-vetinari** [comment]
Something is seriously messing up the solver here, to climb down 11(!) clang major versions, or >6 years worth of compiler upgrades...
```
The reported errors are:
- Encountered problems while solving:
-   - package clangdev-3.8.1-0 requires llvmdev 3.8.1, but none of the providers can be installed
```

**Comment by h-vetinari** [comment]
So https://github.com/conda-forge/qt-main-feedstock/pull/93 will fix this, but the better longterm fix would be to solve https://github.com/conda-forge/clangdev-feedstock/issues/196

**Comment by hmaarrfk** [comment]
I believe this can be closed right?

**Comment by h-vetinari** [comment]
Closing as fixed in #162

**Pull request closed without merging**
