### PR TITLE
Pyside6 vulkan

### PR DESCRIPTION
**Pull request by hmaarrfk**
seems like they are looking for the vulkan headers too

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@jschueller do you know if there is anything we do to check if the vulkan and wayland bindings are correclty built? is there anything that gets built?

**Comment by hmaarrfk** [comment]
@jan-janssen why did you think this did anything?

im not convinced anything of substance happened

**Comment by jan-janssen** [comment]
@hmaarrfk I am sorry, I guess I was too quick with merging this. Do you want me to revert it?

**Comment by hmaarrfk** [comment]
well maybe it would  be good to revert because i'm not sure we did anything of use.

maybe we can run a diff on the generate dbinaries.

**Pull request merged**
