### PR TITLE
linux-aarch64

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
@conda-forge/core rerendering is broken with:
```
2022-09-10T16:11:05.5124301Z Traceback (most recent call last):
2022-09-10T16:11:05.5125504Z   File "/opt/conda/bin/conda-smithy", line 10, in <module>
2022-09-10T16:11:05.5215366Z     sys.exit(main())
2022-09-10T16:11:05.5215965Z   File "/opt/conda/lib/python3.8/site-packages/conda_smithy/cli.py", line 681, in main
2022-09-10T16:11:05.5216287Z     args.subcommand_func(args)
2022-09-10T16:11:05.5216855Z   File "/opt/conda/lib/python3.8/site-packages/conda_smithy/cli.py", line 486, in __call__
2022-09-10T16:11:05.5217165Z     self._call(args, tmpdir)
2022-09-10T16:11:05.5217580Z   File "/opt/conda/lib/python3.8/site-packages/conda_smithy/cli.py", line 491, in _call
2022-09-10T16:11:05.5217880Z     configure_feedstock.main(
2022-09-10T16:11:05.5218342Z   File "/opt/conda/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 2243, in main
2022-09-10T16:11:05.5218684Z     set_migration_fns(forge_dir, config)
2022-09-10T16:11:05.5219387Z   File "/opt/conda/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 2156, in set_migration_fns
2022-09-10T16:11:05.5219780Z     migrations_in_cfp = get_migrations_in_dir(cfp_migrations_dir)
2022-09-10T16:11:05.5220331Z   File "/opt/conda/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 2103, in get_migrations_in_dir
2022-09-10T16:11:05.5220738Z     yaml.load(contents, Loader=yaml.loader.BaseLoader) or {}
2022-09-10T16:11:05.5221182Z   File "/opt/conda/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
2022-09-10T16:11:05.5221491Z     return loader.get_single_data()
2022-09-10T16:11:05.5221934Z   File "/opt/conda/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
2022-09-10T16:11:05.5222256Z     node = self.get_single_node()
2022-09-10T16:11:05.5222672Z   File "/opt/conda/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
2022-09-10T16:11:05.5223001Z     document = self.compose_document()
2022-09-10T16:11:05.5223453Z   File "/opt/conda/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
2022-09-10T16:11:05.5223769Z     node = self.compose_node(None, None)
2022-09-10T16:11:05.5224205Z   File "/opt/conda/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
2022-09-10T16:11:05.5224549Z     node = self.compose_mapping_node(anchor)
2022-09-10T16:11:05.5225042Z   File "/opt/conda/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
2022-09-10T16:11:05.5225388Z     item_value = self.compose_node(node, item_key)
2022-09-10T16:11:05.5225836Z   File "/opt/conda/lib/python3.8/site-packages/yaml/composer.py", line 82, in compose_node
2022-09-10T16:11:05.5226171Z     node = self.compose_sequence_node(anchor)
2022-09-10T16:11:05.5226621Z   File "/opt/conda/lib/python3.8/site-packages/yaml/composer.py", line 110, in compose_sequence_node
2022-09-10T16:11:05.5226982Z     while not self.check_event(SequenceEndEvent):
2022-09-10T16:11:05.5227431Z   File "/opt/conda/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
2022-09-10T16:11:05.5227740Z     self.current_event = self.state()
2022-09-10T16:11:05.5228216Z   File "/opt/conda/lib/python3.8/site-packages/yaml/parser.py", line 403, in parse_indentless_sequence_entry
2022-09-10T16:11:05.5228569Z     if self.check_token(BlockEntryToken):
2022-09-10T16:11:05.5229002Z   File "/opt/conda/lib/python3.8/site-packages/yaml/scanner.py", line 115, in check_token
2022-09-10T16:11:05.5229302Z     while self.need_more_tokens():
2022-09-10T16:11:05.5229733Z   File "/opt/conda/lib/python3.8/site-packages/yaml/scanner.py", line 152, in need_more_tokens
2022-09-10T16:11:05.5230059Z     self.stale_possible_simple_keys()
2022-09-10T16:11:05.5230508Z   File "/opt/conda/lib/python3.8/site-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
2022-09-10T16:11:05.5230887Z     raise ScannerError("while scanning a simple key", key.mark,
2022-09-10T16:11:05.5231223Z yaml.scanner.ScannerError: while scanning a simple key
2022-09-10T16:11:05.5231521Z   in "<unicode string>", line 7, column 1:
2022-09-10T16:11:05.5231731Z     boost_cpp
2022-09-10T16:11:05.5231917Z     ^
2022-09-10T16:11:05.5232164Z could not find expected ':'
2022-09-10T16:11:05.5232505Z   in "<unicode string>", line 8, column 1:
2022-09-10T16:11:05.5232766Z     - 1.78.0
```

**Comment by hmaarrfk** [comment]
Fixed in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3404
and more long term in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3405

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
error:
```
fatal error: 'type_traits' file not found
```

**Comment by hmaarrfk** [comment]
it seems like we are missing an include directory maybe?

**Comment by hmaarrfk** [comment]
I feel like we need to add:
```
+    - sysroot_linux-64 2.17                  # [linux]
```

But ultimately, it seems to me that something in the shiboken build is leaving a trail that doesn't work for the pyside2 build.

I get the same error when trying to use an external shiboken2 build.

**Comment by hmaarrfk** [comment]
```
2022-09-10T16:45:11.0722845Z (shiboken) Unable to start /home/conda/feedstock_root/build_artifacts/pyside2_1654270119706/_build_env/bin/x86_64-conda-linux-gnu-c++: execvp: No such file or directory
```

**Comment by hmaarrfk** [comment]
Is it ok if we merge the 5.15.6 first?

**Comment by looooo** [comment]
sure :+1:

**Comment by hmaarrfk** [comment]
I think it might be worthw
[sources/pyside2/cmake/MacrosPySideModules.cmake](https://github.com/conda-forge/pyside2-feedstock/files/9543092/PySideModules.cmake.txt)
hile studying the file

specifically
```cmake
    # Contains include directories to pass to shiboken's preprocessor.
    # Workaround: Added ${QT_INCLUDE_DIR}/QtCore until
    # qtdeclarative/8d560d1bf0a747bf62f73fad6b6774095442d9d2 has reached qt5.git
    string(REPLACE ";" ${PATH_SEP} core_includes "${Qt5Core_INCLUDE_DIRS}")
    set(shiboken_include_dirs ${pyside2_SOURCE_DIR}${PATH_SEP}${QT_INCLUDE_DIR}${PATH_SEP}${core_includes})
    set(shiboken_framework_include_dirs_option "")
    if(CMAKE_HOST_APPLE)
        set(shiboken_framework_include_dirs "${QT_FRAMEWORK_INCLUDE_DIR}")
        make_path(shiboken_framework_include_dirs ${shiboken_framework_include_dirs})
        set(shiboken_framework_include_dirs_option "--framework-include-paths=${shiboken_framework_include_dirs}")
    endif()
```

**Comment by looooo** [comment]
thanks to @hmaarrfk for doing the hard work to enable linux-aarch64 for pyside2. I am now trying to build freecad for linux-aarch64 locally, but I am running into a dependency issue. Also I am not yet able to update to qt5.15.6. Is there still something missing?

**Comment by hmaarrfk** [comment]
link or log to issue?

**Pull request closed without merging**
