### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by mbargull** [comment]
Hi @jschueller, please be aware that `conda-forge` also builds packages off of non-`master` branches. Thus you PR was already released.

**Comment by mbargull** [comment]
Can you remove this branch and work on your changes in a fork, please?

**Comment by mbargull** [comment]
Thanks!

**Comment by jakirkham** [comment]
So I think what happened is Julien tried to use the nice GitHub online editing feature to make changes. Unfortunately that feature is really half baked. The result is GitHub adds branches to the repo one is trying to edit instead of on one's fork as is typical. Trying to do the latter ends up requiring going through several hoops, which is really not user friendly. This is hardly the first time a maintainer got messed up because of this issue (many of core have ran into the same problem).

It's high time for us to write an email to GitHub stating that they need to fix this feature to add branches to the user's fork instead (even if they have push permissions to the repo). This feature would be really nice for a lot of maintainers, but GitHub needs to be made aware of the problems and how many people are affected. Would be happy to help write this email, but would be ok if someone else takes charge.

cc @conda-forge/core

**Comment by xoviat** [comment]
I've long been frustrated by the limitations of the web editor. +1 from me.

**Pull request closed without merging**
