### PR TITLE
Update to 6.7.0

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
I would appreciate if we could get qt6-wayland working.

One of 
* https://github.com/conda-forge/qt-main-feedstock/pull/256
* https://github.com/conda-forge/qt-main-feedstock/pull/258

Could be merged to enable the fix.

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
thanks for working through things!

**Pull request merged**
