### PR TITLE
Python3.10 patching

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
there is still a windows/python3.10 issue:
´%SRC_DIR%\sources\shiboken2\libshiboken\signature.cpp(949): error C2065: 'ssize_t': undeclared identifier`

@jschueller

**Comment by looooo** [comment]
@conda-forge-admin, please restart ci

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@conda-forge-admin, please restart ci

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
