### PR TITLE
Avoid qt-main clobbering

### PR DESCRIPTION
**Pull request by traversaro**
Fix and add tests for https://github.com/conda-forge/pyside2-feedstock/issues/223 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
Existing checks seems to be working fine  thanks to https://github.com/conda-forge/pyside2-feedstock/pull/222, @hmaarrfk do you hae any additional test that you think it could make sense to add?

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
i know that it removes more just `uic` can you list out the binaries that we miss?

**Comment by traversaro** [comment]
> i know that it removes more just `uic` can you list out the binaries that we miss?

The relevant code is https://github.com/pyside/pyside-setup/blob/dev/sources/pyside-tools/CMakeLists.txt#L35-L60 . All the tools that are skipped by the `NO_QT_TOOLS` actually come from the qt6 installation prefix, the precise list is:
* uic
* rcc
* qmltyperegistrar
* qmlimportscanner
* qmlcachegen
* lrelease
* lupdate
* qmllint
* qmlformat
* qmlls
* qsb
* balsam
* balsamui

On Apple platform, the directories:
* `Assistant.app`
* `Designer.app`
* `Linguist.app`

while on non-Apple platform, also the following commands:
* assistant
* designer
* linguist

The `NO_QT_TOOLS` is used in mingw packaging (https://github.com/msys2/MINGW-packages/blob/3410183e8d0d2d3fe65313c0c3f4a7909df55889/mingw-w64-pyside6/PKGBUILD#L91), homebrew (https://github.com/Homebrew/homebrew-core/blob/2461efa1197635f5bd546536a7ace1c6b9ab3535/Formula/p/pyside.rb#L78) and archlinux (https://gitlab.archlinux.org/archlinux/packaging/packages/pyside6/-/blob/8f9efdc1531d6a9776c1d4b223564645c44bccf4/PKGBUILD#L63).

**Comment by hmaarrfk** [comment]
Alright thanks. Let’s go with this and see where it goes

**Pull request merged**
