### PR TITLE
V5.15.4

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
i just can't understand why it is giving this error on 3.8, but not 3.7.

**Comment by hmaarrfk** [comment]
The problematic line of code seems to be around this:
https://github.com/pyside/pyside2-setup/blob/5.15/sources/pyside2/PySide2/__init__.py.in#L53

**Comment by hmaarrfk** [comment]
seems like it is working!

**Comment by hmaarrfk** [comment]
The two things I noticed looking at hte logs are:

- [ ] Do we need to explicitely depend on `ucrt`? Windows builds seem to be warning for it.
- [ ] How do we actually get the windows tests to work? It seems they all fail due to some inconsistencies with paths.
- [ ]

**Comment by jan-janssen** [comment]
@hmaarrfk I am happy to merge this whenever you are ready. Great work!

**Review by jan-janssen — APPROVED** [review]

**Comment by hmaarrfk** [comment]
I think this is working. But I'm just not sure about windows since I don't have too much experience on it

**Comment by jan-janssen** [comment]
Ok, I merged it and then we just see if some windows users complain.

**Comment by jan-janssen** [comment]
@hmaarrfk btw. feel free to add yourself to the maintainers.

**Pull request merged**
