### PR TITLE
defaultFramebufferObject

### PR DESCRIPTION
**Pull request by jschueller**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
for my education, could you explain what you are looking for?

**Comment by jschueller** [comment]
hello, I think I found the cause of #45

**Comment by psobolewskiPhD** [comment]
🎉 
I can confirm the issue is solved!
`hasattr(QOpenGLWidget, "defaultFramebufferObject")`
reports `True` on macOS 13.1 arm64 for pyside2 build live on conda-forge.
Huge thanks! 🙏

**Pull request merged**
