### PR TITLE
Go back to 5.12.x

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by jschueller** [comment]
could someone from @conda-forge/core mark all pyside2 packages in version 5.13.1 as broken on the repo (or delete) ? it turned out that building > 5.12.x (we have qt.12) is not supported and could lead to inconsistencies

**Comment by hmaarrfk** [comment]
Why?

**Comment by hmaarrfk** [comment]
```
Trying to compile pysid2 5.14 with qt5.12.5 for conda-forge we see failing builds due to missing symbol MessageLogContext::copy. Any ideas what's wrong here?
conda-forge/pyside2-feedstock#59
I know absolutely 0 of C++, @cmaureir , I wouldn't know where to start. But the desired functionality as per documentation is not working with that one. No idea if it's a pyside bug or a qt bug. It was tested on Pyside 5.13.2
Is uic and rcc tools more parts of PySide2 project or are they in other Qt subproject, please? (Just to report this small bug right: https://bugreports.qt.io/browse/PYSIDE-1183)
@looooo that will not work. Please build PySide2 on the same version as Qt, otherwise, you would need to do many modifications to the typesystem, and more. I feel your pain with conda-forge, but PySide2 needs to stick with what conda-force provides for Qt.
@Aens luckily for you, there is a soon-to-be-merge Python to C++ magical script :) stay tuned!
@milos-korenciak the main issue is that we drop the hacky out of date pyside2-uic/rcc versions we had (forked from PyQt long time ago) and replace them with the official Qt uic/rcc. You did right with reporting that on PySide2, because we need to control the Python improvements to uic/rcc in Qt. But sadly I will close your issue, since that was already and solved. it will be available in the next 5.14 release.
@cmaureir Why sadly? I am very happy it has been fixed ;)
```

**Comment by jschueller** [comment]
see #62

**Pull request closed without merging**
