### PR TITLE
Update to 5.14.0

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by looooo** [comment]
All platforms failing because of different errors. That's frustrating. How to continue?

**Comment by hmaarrfk** [comment]
start with your favorite platform. 

Add a 

```
skip: true  # [not XXXX]
```

to make builds faster and rerender.

Are you supposed to be able to compile 5.14 with 5.12???

FWIW, I've had alot of trouble compiling with qt 5.12.5, I had to downgrade to 5.12.1 for some platforms, you cna then use 5.12.5 in runtime it seems

https://github.com/conda-forge/opencv-feedstock/blob/master/recipe/meta.yaml#L78

**Comment by looooo** [comment]
@hmaarrfk 
> Are you supposed to be able to compile 5.14 with 5.12???

I guess it should work.

> FWIW, I've had alot of trouble compiling with qt 5.12.5, I had to downgrade to 5.12.1 for some platforms, you cna then use 5.12.5 in runtime it seems

Good idea. I think zhe last build of pyside2 was done with 5.12.1 too.

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Pull request closed without merging**
